version: '3.8'
services:
  postgres:
    image: "postgres:latest"
    restart: always
    volumes:
      - $HOME/MobSF/postgresql_data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mobsf
    ports:
      - "5432:5432"
    networks:
        - mobsf
      
  mobsf:
    environment: 
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=mobsf
      - DB_HOST=postgres
    build:
      context: .
      dockerfile: Dockerfile
      args:
        api_key: "a00a00a00a00a"
    ports:
     - "8000:8000"
    networks:
      - mobsf
    depends_on:
      - postgres
    links:
      - "postgres"
networks:
  mobsf:
